version: "3"

services:
  jenkins:
    build: .
    container_name: jenkins
    restart: always
    ports:
      - 8080:8080
    environment:
      JENKINS_OPTS: --prefix=/jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins_home:/var/jenkins_home
